### ISSUE TITLE
Typos + suggestion

### ISSUE THREAD

**Issue by nicotriballier** [oktadeveloper/okta-spring-boot-oauth-example#3]
Hi Matt,
gr8 tutorial. Here's some feedback:
1) there's a typo:
	its not *spring run helloGroovy.groovy* its *spring run helloWorld.groovy*
2) i think that would be nice to add a screenshot of what the .yaml file should look like when we added the values from the auth server metadata (see screenshot below):
![image](https://user-images.githubusercontent.com/30125573/35006686-1294c882-faac-11e7-8cc5-0c448854dc10.png)

**Comment by mraible** [comment]
Thanks for the bug report and suggestion @nicolastriballier-okta. I'll fix 1 and add more information to the existing listing to fix 2. I'm not going to add a screenshot because people can't copy and paste and it's not a good idea to publish client IDs and secrets.

**Comment by mraible** [comment]
Fixed by https://github.com/okta/okta.github.io/pull/1715.
