### ISSUE TITLE
Okta SAML SSO for Spring Boot Web Application

### ISSUE THREAD

**Issue by qentelliuser2** [oktadeveloper/okta-spring-boot-oauth-example#6]
Hi Team,

Am trying to integrate Okta SAML into spring boot application, plus adding authentication with using spring security.

Steps to Reproduce: 
1. Login with Okta Credentials 
2. Click on the MyApp(Created as SAML 2.0 app)
3. It will Redirect to Single Sign On URL like (https://localhost:8443/saml/SSO)
4. But am getting below error

**java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens**

Attached is the code that i have developed, can you please help me out !

[okta_saml_springboot.zip](https://github.com/oktadeveloper/okta-spring-boot-oauth-example/files/3419829/okta_saml_springboot.zip)

**Comment by mraible** [comment]
Hello,

Can you please try this tutorial that uses Spring Boot and SAML?

https://developer.okta.com/blog/2017/03/16/spring-boot-saml

I’m closing this issue since it has nothing to do with this repository.
